version: "3.8"

services:
  api:
    container_name: go-server
    build: .
    restart: always
    env_file:
      - .env
    environment:
      DATABASE_URL: "host=postgresql_db user=postgres password=postgres dbname=library sslmode=disable"
    depends_on:
      - postgresql-db
    ports:
      - 3000:3000
      
  postgresql-db:
    container_name: postgresql_db
    image: postgres:alpine
    restart: always
    environment: 
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: library
    ports:
      - 5432:5432
    volumes: 
      - postgres:/var/lib/postgresql/data
  
  redis-cache:
    container_name: redis-cache
    image: redis
    restart: always
    ports:
      - 6379:6379

 
volumes:
  postgres:
  