version: "3.9"

services:
  api:
    container_name: go-server
    build:
      context: .
      dockerfile: build/Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      DATABASE_URL: "host=postgresql user=postgres password=postgres dbname=library sslmode=disable"
    depends_on:
      - postgresql-db
      - redis-cache
    ports:
      - 3000:3000
    networks:
      - library_network
      
  postgresql-db:
    container_name: postgresql
    image: postgres:alpine
    restart: always
    environment: 
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: library
    ports:
      - 5432:5432
    volumes: 
      - postgres:/var/lib/postgresql/data
    networks:
      - library_network
  
  redis-cache:
    container_name: redis
    image: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - library_network

 
volumes:
  postgres:

networks:
  library_network:
  